# Help:  https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

variables:
  mainVersion: '0'
  tag: '$(mainVersion).$(Build.BuildId)'
  image-name:  vplauzon/jekyll-serve
  docker-registry-endpoint:  'vplauzon-docker-hub'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: '$(image-name)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: '$(docker-registry-endpoint)'
        repository: '$(image-name)'
        command: 'push'
        tags: '$(tag)'
- stage: Release
  displayName: Release
  jobs:  
  - job: Tag
    displayName: Tag latest version
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Pull image
      inputs:
        containerRegistry: '$(docker-registry-endpoint)'
        repository: '$(image-name)'
        customCommand: 'pull $(image-name):$(tag)'
    - task: Docker@2
      displayName: Tag image
      inputs:
        containerRegistry: '$(docker-registry-endpoint)'
        repository: '$(image-name)'
        customCommand: 'tag $(image-name):$(tag) $(image-name):$(mainVersion)'
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: '$(docker-registry-endpoint)'
        repository: '$(image-name)'
        command: 'push'
        tags: '$(mainVersion)'
