# Help:  https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

variables:
  mainVersion: '0.1'
  tag: '$(mainVersion).$(Build.BuildId)'
  image-name:  vplauzon/jekyll-serve
  docker-registry-endpoint:  'vplauzon-docker-hub'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: '$(image-name)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: '$(docker-registry-endpoint)'
        repository: '$(image-name)'
        command: 'push'
        tags: '$(tag)'
    - task: Bash@3
      displayName: Pull, tag & push
      inputs:
        targetType: 'filePath'
        filePath: pull-tag-push.sh
        arguments: $(image-name) $(tag) experimental
    - task: PublishBuildArtifacts@1
      displayName: "Publish artifact:  scripts"
      inputs:
        PathtoPublish: scripts
        ArtifactName: scripts
- stage: Production
  displayName: Production
  dependsOn:  Build
  jobs:
    - template: tag-jobs.yaml
      parameters:
        environment:  production
        targetVersion:  $(mainVersion)